### ISSUE TITLE
Test Runner for Java Extension downloads old JUnit standalone

### ISSUE THREAD

**Issue by joaocaram** [microsoft/vscode-java-test#1866]
When we create a "no build tools" Java project and, after that, try to "Enable Java Tests" using the "test icon", it downloads the "junit-platform-console-standalone-1.13.0-M3.jar" file instead of JUnit 6 versions. This old version is not working with most recent Test Runner and Language Support for Java Extensions.  (i'm using Extension Pack for Java 0.31.0, Language Support 1.54.0 and Test Runner 0.45.0).

<img width="712" height="526" alt="Image" src="https://github.com/user-attachments/assets/9bc4a34a-2b69-4f10-bd96-3421ec192ffa" />

<img width="432" height="257" alt="Image" src="https://github.com/user-attachments/assets/d8bfcfae-d9eb-450c-9d38-70cde0775e89" />

I know we can fix it by manually downloading more recent standalones, or creating Maven/Gradle projects. But when the platform is being used to teach some dozen first-term students, creating a Maven project, keep in mind the directories and packages structure etc are annoying and time consuming distractions. 

Besides, if there is a plugin to make things easier for everyone (such as downloading and including the reference to the Junit jar), it should work properly. So, please, take a few minutes to fix this.

**Comment by joaocaram** [comment]
Hi AI/bot @github-actions

>     * Upvote or comment on the existing feature request to bump the default standalone JAR version in the Test Runner extension so the next release ships a recent JUnit platform.

Sorry, I may be missing something here. Where do I find the feature request so I can upvote? 

Thanks

**Comment by wenytang-ms** [comment]
Looked into this. The root cause is actually two bugs working together:

1. **`Enable Java Tests` downloads a Platform 1.x jar** ([`testDependenciesCommands.ts:81,138-142`](https://github.com/microsoft/vscode-java-test/blob/main/src/commands/testDependenciesCommands.ts#L81)): the `JUnit5` branch asks Maven Central's search API for `latestVersion` of `org.junit.platform:junit-platform-console-standalone`, which currently returns `1.13.x`.
2. **Test kind dispatch then misclassifies that 1.x jar as JUnit 6** ([`TestKindProvider.java:48-53`](https://github.com/microsoft/vscode-java-test/blob/main/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/provider/TestKindProvider.java#L48), introduced in #1820): we delegate to `CoreTestSearchEngine.hasJUnit6TestAnnotation`. For `junit-platform-console-standalone-*.jar` the filename does not match the `junit-platform-commons` prefix and the manifest has no `Specification-Version`, so JDT cannot determine the platform version and falls through, returning `true`. The launcher then picks `org.eclipse.jdt.junit6.runtime`, which hard-requires Platform 6.0 APIs (`CancellationToken`, `LauncherExecutionRequest`…) → `NoClassDefFoundError` at runtime.

Same root cause as the `NoClassDefFoundError: org/junit/platform/engine/CancellationToken` reported in [redhat-developer/vscode-java#4396](https://github.com/redhat-developer/vscode-java/issues/4396#issuecomment-4598913340).

I will send a PR shortly to add a Platform 6 sentinel check in `TestKindProvider` so 1.x fat jars correctly dispatch to the JUnit 5 runner. That fixes the runtime failure for both new `Enable Tests` installs and existing JUnit 5 projects.

**Comment by CherryDT** [comment]
Same issue here (see https://github.com/redhat-developer/vscode-java/issues/4396#issuecomment-4599546584).

I was told it's a bug with `vscode-java-test`, not `vscode-java`, but if I downgrade `vscode-java` to 1.53, it all works, so I'm not sure what exactly the problem is.

Anyway, I believe a) existing projects using the 1.13 JAR should continue working, and b) "Enable Java tests" should not install something by default that is broken.

**Comment by wenytang-ms** [comment]
Update: after closer analysis we are going to **rely on the upstream JDT fix** rather than ship a downstream workaround in this repo.

**Upstream fixes already merged:**
- [eclipse-jdt/eclipse.jdt.ui#2910](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2910) — fixes the annotation-anchor and JUnit 5 major-version baseline.
- [eclipse-jdt/eclipse.jdt.ui@17f8fa5](https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/17f8fa5d9f96a9158eb40943a7f5e424e0292ee7) (Fixes [eclipse-jdt/eclipse.jdt.ui#2959](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2959)) — for `junit-platform-console-standalone-*.jar`, reads the bundled Jupiter engine version from the manifest's `Engine-Version-junit-jupiter` attribute so version detection returns `5.x` instead of mistaking the platform's `1.x`.

**Why not a downstream workaround:** `TestKindProvider` is intentionally a thin wrapper over `CoreTestSearchEngine.hasJUnit5/6TestAnnotation`. Duplicating sentinel-class checks here would just need to be cleaned up later once the upstream fix flows down, and would not help any caller that goes through `CoreTestSearchEngine` directly.

**Release chain (expected timeline):**
1. Eclipse 4.40 release (~mid-June 2026)
2. JDT-LS picks up new JDT jars (target tracks `4.40-I-builds`)
3. vscode-java bumps the bundled JDT-LS server jar
4. End users update their vscode-java extension

This issue will stay open until step 4 is verified. If anyone hits a fat-jar shape that is **not** `junit-platform-console-standalone-*.jar` and still misdispatches to the JUnit 6 runner after upgrading, please post the project setup here — we'll revisit a downstream check at that point.

(The previously proposed PR #1867 has been converted into a tracking record for this decision.)

**Comment by wenytang-ms** [comment]
Fix shipped in pre-release **`0.45.2026060403`**. "Enable Java Tests" now reads the latest version from `maven-metadata.xml`, and JUnit Jupiter 6 is exposed as a separate option (recommended). Selecting JUnit 5 downloads `junit-platform-console-standalone-1.14.4.jar`; selecting JUnit Jupiter 6 downloads `6.1.0`.

Please install the pre-release and verify. Closing as fixed — feel free to reopen if it still misbehaves.

**Comment by joaocaram** [comment]
Hi @wenytang-ms,

> Please install the pre-release and verify. Closing as fixed — feel free to reopen if it still misbehaves.

It worked perfectly with the pre-release. The JUnit 6 recommendation is a nice plus. Thank you!

**Comment by CherryDT** [comment]
I tried updating both `vscode-java` and `vscode-java-test` to pre-release but it doesn't work, now the test options no longer show up at all and I have this in the output console:

```
Jun 04, 2026 5:30:31 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
[Error - 5:30:35 PM] Jun 4, 2026, 5:30:34 PM FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [124]
  Unresolved requirement: Require-Bundle: org.objectweb.asm; bundle-version="[9.9.0,9.10.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:495)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2110)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:146)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2101)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2041)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:2003)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1915)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)

[Error - 5:30:36 PM] Jun 4, 2026, 5:30:36 PM Failed to load extension bundles 
org.eclipse.core.runtime.CoreException: Load bundle list
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:175)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:100)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:68)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:287)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:86)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Contains: Bundle startup failed reference:file:/home/david/.vscode-server/extensions/vscjava.vscode-java-test-0.45.2026060403/server/com.microsoft.java.test.plugin-0.43.1.jar
org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [152]
  Unresolved requirement: Require-Bundle: org.objectweb.asm; bundle-version="[9.9.0,9.10.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:495)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:471)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.startBundles(BundleUtils.java:310)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:173)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:100)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:68)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:287)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:86)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Contains: Bundle startup failed reference:file:/home/david/.vscode-server/extensions/vscjava.vscode-java-test-0.45.2026060403/server/org.jacoco.core_0.8.14.202510111229.jar
org.osgi.framework.BundleException: Could not resolve module: org.jacoco.core [177]
  Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.9.0,9.10.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:495)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:471)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.startBundles(BundleUtils.java:310)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:173)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:100)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:68)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:287)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:86)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Jun 04, 2026 5:30:37 PM com.microsoft.java.debug.plugin.internal.JavaDebuggerServerPlugin start
INFO: Starting com.microsoft.java.debug.plugin
```

No user-visible error beyond the log.

Please advise.

**Comment by wenytang-ms** [comment]
@CherryDT
fixed on #1872, will ship prerelease tomorry.

**Comment by wenytang-ms** [comment]
@CherryDT try install this extension to verify this issue

<img width="838" height="640" alt="Image" src="https://github.com/user-attachments/assets/55122e41-d625-41fe-880b-1cc466e1d57d" />

**Comment by CherryDT** [comment]
Now the tests show up again, but they still fail with the error from before:

```

java.lang.NoClassDefFoundError: org/junit/platform/engine/CancellationToken
	at org.eclipse.jdt.internal.junit6.runner.JUnit6TestReference.<init>(JUnit6TestReference.java:48)
	at org.eclipse.jdt.internal.junit6.runner.JUnit6TestLoader.createUnfilteredTest(JUnit6TestLoader.java:88)
	at org.eclipse.jdt.internal.junit6.runner.JUnit6TestLoader.createTest(JUnit6TestLoader.java:69)
	at org.eclipse.jdt.internal.junit6.runner.JUnit6TestLoader.loadTests(JUnit6TestLoader.java:56)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:579)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:824)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:494)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:225)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.CancellationToken
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 8 more
```

**Comment by wenytang-ms** [comment]
@CherryDT
Looks like your project may still be using the old JUnit standalone jar.
 
 Could you try this:
 
  1. Delete the old junit-platform-console-standalone-1.13.*.jar from your project’s lib folder.
  2. Check .classpath and remove the entry pointing to that old jar if it’s still there.
  3. Run Enable Java Tests again.
  4. Choose JUnit Jupiter 6 (recommended).
  5. Reload VS Code, or run Java: Clean Java Language Server Workspace.
 
 After that, please check that the project is using junit-platform-console-standalone-6.1.0.jar.
 
 If it still fails, could you share your .classpath and the list of jars under lib?

**Comment by CherryDT** [comment]
Yes, it's using the old JUnit standalone jar, I'm not at liberty to change that for all projects I'm working on.

But why would this be a problem? Again, shouldn't the extension keep working with existing projects that have the 1.13 standalone JAR that used to work fine? In my opinion this is a regression. It should detect the JUnit version and use the code path that always worked before.

I feel like we are going in circles, because you already agreed with me on that point before, here: https://github.com/redhat-developer/vscode-java/issues/4396#issuecomment-4599546584

> And you are right that **existing JUnit 5 projects should keep working**.

And here: https://github.com/redhat-developer/vscode-java/issues/4396#issuecomment-4608392680

> Once that fix is released and the next JDT-LS server is bundled into vscode-java, **your existing 1.13 jar** will be routed back to the JUnit 5 runner the way it used to be. **You do not need to migrate to JUnit 6 or swap any jars**. 

(I still get the feeling I'm talking with an AI. Please, please, make sure a human is reading my messages, it's incredibly frustrating. If I'm wrong - sorry, no insult intended, and I appreciate the work you do, I just really don't like the feeling of going in circles.)

**Comment by wenytang-ms** [comment]
You’re right. Replacing the jar is only a workaround, not the real fix.
 
 The expected behavior is still that existing projects using `junit-platform-console-standalone-1.13.x` continue to work as JUnit 5 projects. They should not be forced to migrate to JUnit 6.
 
 The real fix is in the JDT/JDT-LS side: the standalone 1.13.x jar needs to be detected as Jupiter 5.x and routed to the JUnit 5 runner. That fix has already been made upstream, but it still needs to flow through JDT-LS and then into a `redhat.java` / vscode-java release.
 
 To be transparent, I maintain the `vscode-java-test` side, but I do not maintain JDT-LS or the `redhat.java` release pipeline, so I cannot directly control when that fix ships there. I can only track it and verify once a build containing the fix is available.
 
 So for now there are two options:
 
 1. If changing the project dependency is acceptable as a temporary workaround, remove the old `junit-platform-console-standalone-1.13.x.jar`, run **Enable Java Tests** again, and choose **JUnit Jupiter 6**.
 2. If the project must stay unchanged, please stay on `redhat.java` 1.53 for now. Once vscode-java ships a JDT-LS build containing the upstream fix, the existing 1.13.x jar should work again without changing project dependencies.
 
 We’ll keep this tracked as a release-chain issue, not as “fixed by replacing the jar”.

**Comment by CherryDT** [comment]
OK, thanks, but you are again contradicting yourself, because you [closed this as completed 5 days ago](https://github.com/microsoft/vscode-java-test/issues/1866#event-26321570371) and previously you wrote this here: https://github.com/microsoft/vscode-java-test/issues/1866#issuecomment-4600471119

> **Release chain (expected timeline):**
> 
> 1. Eclipse 4.40 release (~mid-June 2026)
> 2. JDT-LS picks up new JDT jars (target tracks `4.40-I-builds`)
> 3. vscode-java bumps the bundled JDT-LS server jar
> 4. End users update their vscode-java extension
> 
> **This issue will stay open until step 4 is verified.** If anyone hits a fat-jar shape that is **not** `junit-platform-console-standalone-*.jar` and still misdispatches to the JUnit 6 runner after upgrading, please post the project setup here — we'll revisit a downstream check at that point.

You said, this issue would stay open until the upstream fix is completed, merged into `vscode-java` _and_ end-users updated `vscode-java`, so it should work. Given that you did close the issue already, I assumed that already happened, but you just said it did not. That's where my confusion came from.

**Comment by wenytang-ms** [comment]
You’re right that the status was confusing.
 
 To clarify: this issue covered the `vscode-java-test` side, and that part is fixed: the new Enable Java Tests flow no longer installs the stale version, JUnit 5/6 are split, and the ASM startup issue is fixed.
 
 The remaining failure with existing `junit-platform-console-standalone-1.13.x` projects is the same end-to-end issue tracked in redhat-developer/vscode-java#4396. The required JDT fix exists upstream, but it still needs to be included in JDT-LS and then shipped by `redhat.java`.
 
 So for existing projects that must keep the 1.13.x jar, the current safe option is still to stay on `redhat.java` 1.53 until #4396 is resolved. Replacing the jar with JUnit Jupiter 6 is only a workaround.

**Comment by CherryDT** [comment]
> until #4396 is resolved

Wait, but [over there](https://github.com/redhat-developer/vscode-java/issues/4396), you wrote:

> @datho7561 just close this issue as fixed — please reopen if it reproduces on a clean setup.

...and...

> Closing this issue since the original Cannot find @Testable part is fixed, and the new CancellationToken symptom is tracked upstream at https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2959.

(although you never actually closed it, even though said "closing this issue".)

So, is https://github.com/redhat-developer/vscode-java/issues/4396 considered fixed or not...?

Plus, the [eclipse-jdt issue you linked](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2959) was closed already in April!

**Comment by wenytang-ms** [comment]
To avoid mixing several fixed and pending parts in this thread, I opened a dedicated tracking issue for the remaining end-to-end case: #1873.
 
 This issue stays closed for the `vscode-java-test` fixes. The new tracking issue covers the remaining release-chain step: JDT-LS / `redhat.java` shipping the upstream JDT fix needed for existing `junit-platform-console-standalone-1.13.x` projects.
