### ISSUE TITLE
NoClassDefFoundError when project applies java-test-fixtures plugin

### ISSUE THREAD

**Issue by disturbedsaint** [microsoft/vscode-java-test#1073]
I have a gradle based multi-project build with 2 sub-projects. `proj2`is a simple library applies the `java-test-fixtures` plugin. `proj1` depends on `proj2`. When I attempt to run any test in `proj1` via the `Run Test` (or `Debug Test`) Code Lens link, I get a `java.lang.NoClassDefFoundError` for the library from `proj2`. Looking at the classpath from the Java Test Runner trace logs, I see that the `proj2` path is not included at all (though `/proj2/bin/default` is, but that's not a real path on my system).

Some things to note:
- In this minimal reproduction of my issue, `proj2` doesn't actually have any test fixtures - it simply applies the plugin. In my real-world use case, we do have test fixtures but that's apparently unnecessary.
- Normal language server usage seems to work - vscode knows about the classes, adds the import statement, performs autocompletion, etc.
- Running tests from the command line via `./gradlew build` works as expected.

Here is a minimal reproduction of the issue: [vscode.zip](https://github.com/microsoft/vscode-java-test/files/5340765/vscode.zip)

**Comment by mfussenegger** [comment]
Noticed the same problem in CrateDB. We switched from a custom testOutput configuration to test fixtures. (The custom testOutput configuration worked well with Gradle 6.6.x, but didn't work anymore with Gradle 6.7, see https://github.com/eclipse/buildship/issues/1035).

PR with the change: https://github.com/crate/crate/pull/11290

What may be interesting is that the `java.project.getClasspaths` command does include the testFixtures classpaths. So merging the results from that command into the classpath from the `vscode.java.test.junit.argument` commands' result would get the test execution to work.

**Comment by LetTheAwesomeBegin** [comment]
Also noticed the same thing when using the following [sample project](https://github.com/LetTheAwesomeBegin/gradle-test-fixtures-example) based off [Gradle's documentation](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures).

Eclipse and IntelliJ IDEA executes the included tests successfully.

**Comment by Mahamadovich** [comment]
Got the same issue :( Any plans to fix this?

**Comment by jdneo** [comment]
update: Buildship just released 3.1.6 snapshot recently. I guess the problem can be resolved in the near future.

**Comment by jdneo** [comment]
Hi all,

The [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java)@1.1.0 has been released with the newest buildship. This issue should have been resolved.

Thanks,
