### ISSUE TITLE
After upgrade from vscode-java v0.77.0 to v0.78.0 can't debug tests

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-java-test#1189]
After upgrade [vscode-java](https://github.com/redhat-developer/vscode-java) from v0.77.0 to v0.78.0 can't debug tests, only execute them

##### Environment
- Operating System: Linux
- JDK version: 11
- Visual Studio Code version: 1.55.2
- Java extension version: 0.78.0

##### Steps To Reproduce
1. Open a maven project with JUnit tests
2. Try run the test in debug mode

##### Current Result
An error message appears and the test can't be run

##### Expected Result
Test is run stopping at any break point

##### Additional Informations
I I downgrade to version 0.77.0 everything works as expected.

The error message in the log is: 
`java.lang.NoSuchMethodError: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'`

see: https://github.com/redhat-developer/vscode-java/issues/1915

**Comment by abrahammurciano** [comment]
Can confirm, this issue affects me too.
OS: 5.11.16-arch1-1
redhat.java extension: v0.78.0
vscjava.vscode-java-test extension: v0.29.0

**Comment by snjeza** [comment]
You may want to take a look at microsoft/vscode-java-debug#995 (comment)

**Comment by testforstephen** [comment]
Hi, I just released a hotfix release 0.33.1 for "Debugger for Java" extension. It will work with both vscode-java@0.77.0 and 0.78.0. Please have a try. thanks.
