### ISSUE TITLE
NoClassDefFoundError when running JUnit5 tests

### ISSUE THREAD

**Issue by capozzid** [microsoft/vscode-java-test#971]
Since 0.22.3 the tests don't work anymore when using 

`testImplementation 'org.junit.jupiter:junit-jupiter:5.5.0'`

in my build.gradle file.
It generates the following error: 

`java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineDiscoveryListener`

it works again when I downgrade to 0.22.2, I guess it might be related to #970 but I'm not sure.

I also tried to change the testImplementation line to 'org.junit.jupiter:junit-jupiter:5.6.0' and now it works with the 0.22.3 version.

The problem I have is that it's a big project and I can't change the testImplementation line just because I have a problem with an IDE extension.

**Comment by jdneo** [comment]
I can also reproduce this bug in Eclipse 2020-03.

I've created a bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=561797

**Comment by jdneo** [comment]
Below are several workarounds before the upstream fixed this issue:

- Upgrade the `org.junit.jupiter:junit-jupiter` to `5.6.0`
- Adding `testImplementation('org.junit.platform:junit-platform-launcher:1.5.2')`
- Downgrade the extension to `0.22.2`

**Comment by norricorp** [comment]
I downgraded java test runner from 0.22.3 to 0.22.2. Still get same problem 
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineDiscoveryListener
when running test.
Compiles and runs on command line (a test does fail so would like to debug)

**Comment by csuzdy** [comment]
Downgrading the extension to 0.22.2 didn't help, but adding testImplementation('org.junit.platform:junit-platform-launcher:1.5.2') fixed the issue.

**Comment by pnhung** [comment]
Even downgrade the extension or upgrade jupiter version not help, just add [testImplementation 'org.junit.platform:junit-platform-launcher:1.5.2'] and version MUST 1.5.2, 1.7.0 not work too

**Comment by kingthorin** [comment]
> Upgrade the `org.junit.jupiter:junit-jupiter` to `5.6.0`

Worked for us.

**Comment by PyvesB** [comment]
> Upgrade the `org.junit.jupiter:junit-jupiter` to `5.6.0`

Worked for us as well in a Maven project.

Make sure that there aren't any dependencies in your dependency tree that are transitively causing some of the JUnit versions to be lowered. For example, having both spring-boot-starter-test and junit-jupiter can cause situations like the following, where the main JUnit libraries are on 5.6.2, but the JUnit platform engine is on 1.5.2 instead of 1.6.2:
<img width="760" alt="Screenshot 2020-07-31 at 16 07 41" src="https://user-images.githubusercontent.com/10694593/89042898-fd0f5280-d347-11ea-970a-b62597206b26.png">

**Comment by kim-daeyong** [comment]
> Even downgrade the extension or upgrade jupiter version not help, just add [testImplementation 'org.junit.platform:junit-platform-launcher:1.5.2'] and version MUST 1.5.2, 1.7.0 not work too

it work! thanks

**Comment by MKruschke** [comment]
> Adding testImplementation('org.junit.platform:junit-platform-launcher:1.5.2')
worked for me 👍🏻

**Comment by maciej-salamon-ftm** [comment]
junit-platform-launcher:1.7.1 seems to work fine now

**Comment by manojboot** [comment]
testImplementation('org.junit.platform:junit-platform-launcher:1.5.2')
adding this worked for me
